# Generated by Django 4.1.13 on 2025-12-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('software_name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('db_name', models.CharField(max_length=100)),
                ('db_username', models.CharField(max_length=100)),
                ('db_pass', models.CharField(max_length=255)),
            ],
        ),
    ]
