# Generated by Django 4.1.13 on 2025-12-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_users_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='msg_active',
            field=models.BooleanField(default=False),
        ),
    ]
